### PR TITLE
refactor: use collections.abc import to use with python 3.8 and 3.10

### PR DESCRIPTION
**Pull request by JuanDavidBuitrago**
**Description:** This PR modified collections import for use with Python 3.10. Using or importing the ABCs from `collections` instead of from `collections.abc` is deprecated since Python 3.3, and in 3.10 it will stop working

**ISSUE:** https://github.com/openedx/openedx-events/issues/128

**Dependencies:** None

**Merge deadline:** None

**Installation instructions:** None

**Testing instructions:**

1. Clone this repo and use the branch
2. Create a viertual environment (use Python 3.8)
3. Run `make requirements`
4. Run `make validate`
5. Repeat steps 2, 3, 4 with python 3.10

**Reviewers:**
- [ ] @mariajgrimaldi
- [ ] @felipemontoya 

**Merge checklist:**
- [ ] All reviewers approved
- [ ] CI build is green
- [ ] Version bumped
- [ ] Changelog record added
- [ ] Documentation updated (not only docstrings)
- [ ] Commits are squashed

**Post merge:**
- [ ] Create a tag
- [ ] Check new version is pushed to PyPI after tag-triggered build is
      finished.
- [ ] Delete working branch (if not needed anymore)

**Author concerns:** None

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @JuanDavidBuitrago!  Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.

**Comment by JuanDavidBuitrago** [comment]
Hello @mariajgrimaldi, could you help me? Thanks!!

**Comment by mariajgrimaldi** [comment]
Thanks for the detailed explanation! This looks good to me. Pretty straightforward. I'm just worried about the codecov failure, but I believe it's because those lines are not being covered by a dedicated unittest. I believe the error will disappear after merging. Still, I'm opening an issue to add and standardize more the unittests of the library.

**Review by mariajgrimaldi — APPROVED** [review]

**Comment by openedx-webhooks** [comment]
@JuanDavidBuitrago 🎉 Your pull request was merged!  Please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/openedx-events&entry.867055334=https://github.com/openedx/openedx-events/pull/170&entry.1484655318=https://github.com/JuanDavidBuitrago&entry.752974735=2023-01-19+17:45&entry.1917517419=2023-01-23+14:19&entry.2133058324=Yes) so we can improve your experience in the future.

**Pull request merged**
