### PR TITLE
build: update codecov action to latest version with repo-specific tokens

### PR DESCRIPTION
**Pull request by mariajgrimaldi**
### Description
This PR updates codecov to the latest release which use tokens per repository.

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @mariajgrimaldi! Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


This is currently a draft pull request. When it is ready for our review and all tests are green, click "Ready for Review", or remove "WIP" from the title, as appropriate.

**Comment by mariajgrimaldi** [comment]
Note to reviewer: I plan on ignoring the codecov/project error since it's not related to the current PR.

**Review by felipemontoya — APPROVED** [review]
Reading the update PRs made for some MFEs I think this is correct.

**Comment by openedx-webhooks** [comment]
@mariajgrimaldi 🎉 Your pull request was merged!  Please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/openedx-events&entry.867055334=https://github.com/openedx/openedx-events/pull/339&entry.1484655318=https://github.com/mariajgrimaldi&entry.752974735=2024-04-12+13:15&entry.1917517419=2024-04-18+14:17&entry.2133058324=Yes) so we can improve your experience in the future.

**Pull request merged**
