### PR TITLE
Bump version: 0.12.0 → 0.13.0

### PR DESCRIPTION
**Pull request by mariajgrimaldi**
**Description:** 
This PR bumps the library version references to v0.13.0

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @mariajgrimaldi!

As a core committer in this repo, you can merge this once the pull request is approved per the [core committer reviewer requirements](https://openedx.atlassian.net/wiki/spaces/COMM/pages/1529675973/Open+edX+Core+Committers#Reviews-and-Ownership) and according to the agreement with your edX Champion.

**Review by felipemontoya — APPROVED** [review]
This is a good catch. I'm wondering why previous bumps did not change the setup.cfg

**Comment by mariajgrimaldi** [comment]
The `setup.cfg` is usually updated using the `bumpversion` package, so I suppose this was being updated manually.

**Comment by openedx-webhooks** [comment]
: thought you might like to know that mariajgrimaldi merged this pull request.

**Comment by openedx-webhooks** [comment]
@mariajgrimaldi 🎉 Your pull request was merged!  Please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/openedx-events&entry.867055334=https://github.com/openedx/openedx-events/pull/120&entry.1484655318=https://github.com/mariajgrimaldi&entry.752974735=2022-09-20+13:54&entry.1917517419=2022-09-20+14:12&entry.2133058324=Yes) so we can improve your experience in the future.

**Pull request merged**
