### PR TITLE
docs: change readme structure following maintainers OEP

### PR DESCRIPTION
**Pull request by mariajgrimaldi**
**Description:** 
This PR updates the current readme documentation following the suggestions in the [OEP-55](https://open-edx-proposals.readthedocs.io/en/latest/processes/oep-0055-proc-project-maintainers.html#id23).

**Reviewers:**
- [ ] TBD

**Merge checklist:**
- [ ] All reviewers approved
- [ ] CI build is green
- [ ] Version bumped
- [ ] Changelog record added
- [ ] Documentation updated (not only docstrings)
- [ ] Commits are squashed

**Post merge:**
- [ ] Create a tag
- [ ] Check new version is pushed to PyPI after tag-triggered build is 
      finished.
- [ ] Delete working branch (if not needed anymore)

**Author concerns:** List any concerns about this PR - inelegant 
solutions, hacks, quick-and-dirty implementations, concerns about 
migrations, etc.

### CODE REVIEW

**Comment by mariajgrimaldi** [comment]
Hello @sarina! Some time ago, we talked about restructuring the library readme, so it follows the ideas around OEP-55. I then opened this PR as a draft following the suggestions in the Miro board you shared with me and the OEP. I think I now have the 1st version. Who should we tag? :thinking:

**Comment by sarina** [comment]
Nice job!

You'll want to talk to @feanil - he's on vacation through next week though. I'm sure he'll be happy to help out once he's back!

**Comment by mariajgrimaldi** [comment]
I'll close this PR in favor of: https://github.com/openedx/openedx-events/pull/100

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @mariajgrimaldi!

As a core committer in this repo, you can merge this once the pull request is approved per the [core committer reviewer requirements](https://openedx.atlassian.net/wiki/spaces/COMM/pages/1529675973/Open+edX+Core+Committers#Reviews-and-Ownership) and according to the agreement with your edX Champion.

**Comment by openedx-webhooks** [comment]
@mariajgrimaldi Even though your pull request wasn’t merged, please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/openedx-events&entry.867055334=https://github.com/openedx/openedx-events/pull/57&entry.1484655318=https://github.com/mariajgrimaldi&entry.752974735=2022-05-19+14:51&entry.1917517419=2022-08-31+20:30&entry.2133058324=No) so we can improve your experience in the future.

**Pull request closed without merging**
