### PR TITLE
test: update command for pypi friendly package check

### PR DESCRIPTION
**Pull request by mariajgrimaldi**
**Description:** 
This PR updates command for package generation since, according to the [Python Packaging User Guide](https://packaging.python.org/en/latest/), we should be using twine.

More info: https://packaging.python.org/en/latest/guides/making-a-pypi-friendly-readme/#validating-restructuredtext-markup

**Dependencies:** 
None

**Merge deadline:** 
ASAP

**Installation instructions:** 
Just a tox update. Check out CI docs section for results.

**Testing instructions:**
Just a tox update. Check out CI docs section for results.

**Reviewers:**
- [ ] @felipemontoya 

**Merge checklist:**
- [ ] All reviewers approved
- [x] CI build is green
- [ ] Version bumped
- [ ] Changelog record added
- [ ] Documentation updated (not only docstrings)
- [ ] Commits are squashed

**Post merge:**
- [ ] Create a tag
- [ ] Check new version is pushed to PyPI after tag-triggered build is 
      finished.
- [ ] Delete working branch (if not needed anymore)

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @mariajgrimaldi!

As a core committer in this repo, you can merge this once the pull request is approved per the [core committer reviewer requirements](https://openedx.atlassian.net/wiki/spaces/COMM/pages/1529675973/Open+edX+Core+Committers#Reviews-and-Ownership) and according to the agreement with your edX Champion.

**Review by felipemontoya — COMMENTED** [review]
This set of changes looks good to me.
Do we have any references from other libraries from the open edx project that are also using twine?

**Comment by mariajgrimaldi** [comment]
> This set of changes looks good to me. Do we have any references from other libraries from the open edx project that are also using twine?

Yep! I forgot to tag it:
https://github.com/openedx/edx-ace/blob/master/tox.ini#L23-L28

**Comment by felipemontoya** [comment]
All good. I went searching and found [a bunch](https://github.com/search?q=org%3Aopenedx+twine+check&type=code) of implementations

**Review by felipemontoya — APPROVED** [review]

**Comment by openedx-webhooks** [comment]
: thought you might like to know that mariajgrimaldi merged this pull request.

**Pull request merged**
