### PR TITLE
build: add linter for commit messages

### PR DESCRIPTION
**Pull request by mariajgrimaldi**
**Description:** 
This PR adds a commit lit github workflow to -in the long run- improve commit messages quality,

**Dependencies:** 
None

**Merge deadline:** 
ASAP

**Installation instructions:**
Just another GH workflow.

**Testing instructions:**
Just another GH workflow.

**Reviewers:**
- [x] @felipemontoya 

**Merge checklist:**
- [x] All reviewers approved
- [x] CI build is green
- [ ] Version bumped
- [ ] Changelog record added
- [ ] Documentation updated (not only docstrings)
- [x] Commits are squashed

**Post merge:**
- [ ] Create a tag
- [ ] Check new version is pushed to PyPI after tag-triggered build is 
      finished.
- [ ] Delete working branch (if not needed anymore)

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @mariajgrimaldi!

As a core committer in this repo, you can merge this once the pull request is approved per the [core committer reviewer requirements](https://openedx.atlassian.net/wiki/spaces/COMM/pages/1529675973/Open+edX+Core+Committers#Reviews-and-Ownership) and according to the agreement with your edX Champion.


This is currently a draft pull request. When it is ready for our review and all tests are green, click "Ready for Review", or remove "WIP" from the title, as appropriate.

**Review by felipemontoya — APPROVED** [review]
This looks good.
I was comparing to https://github.com/openedx/DoneXBlock/blob/master/.github/workflows/commitlint.yml

**Comment by openedx-webhooks** [comment]
: thought you might like to know that mariajgrimaldi merged this pull request.

**Comment by openedx-webhooks** [comment]
@mariajgrimaldi 🎉 Your pull request was merged!  Please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/openedx-events&entry.867055334=https://github.com/openedx/openedx-events/pull/101&entry.1484655318=https://github.com/mariajgrimaldi&entry.752974735=2022-08-30+16:05&entry.1917517419=2022-08-31+20:24&entry.2133058324=Yes) so we can improve your experience in the future.

**Pull request merged**
